
	
	
-- Database: TestCase

--DROP DATABASE "TestCase";

CREATE DATABASE "TestCase"
    WITH 
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'Spanish_Spain.1252'
    LC_CTYPE = 'Spanish_Spain.1252'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;
	
	
	-- Table: public.roles

-- DROP TABLE public.roles;

CREATE TABLE public.roles
(
    idrol integer NOT NULL,
    rol character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT roles_pkey PRIMARY KEY (idrol)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;


	-- Table: public.authorities

-- DROP TABLE public.authorities;

CREATE TABLE public.authorities
(
    idauth integer NOT NULL,
    username character varying(30) COLLATE pg_catalog."default" NOT NULL,
    pass character varying(8) COLLATE pg_catalog."default" NOT NULL,
    idrol integer,
    CONSTRAINT authorities_pkey PRIMARY KEY (idauth),
    CONSTRAINT role_user_id_fkey FOREIGN KEY (idrol)
        REFERENCES public.roles (idrol) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.authorities
    OWNER to postgres;
	

	ALTER TABLE public.roles
    OWNER to postgres;
	
-- Table: public.users

 --DROP TABLE public.users;

CREATE TABLE public.users
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    firstname character varying(30) COLLATE pg_catalog."default" NOT NULL,
    iban character varying(50) COLLATE pg_catalog."default" NOT NULL,
    lastname character varying(30) COLLATE pg_catalog."default" NOT NULL,
    createdby integer,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_auth_fk FOREIGN KEY (createdby)
        REFERENCES public.authorities (idauth) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.users
    OWNER to postgres;	
	
	INSERT INTO public.roles(
	idrol, rol)
	VALUES (1, 'administrator');
	
	INSERT INTO public.roles(
	idrol, rol)
	VALUES (2, 'user');INSERT INTO public.authorities(
	idauth, username, pass, idrol)
	VALUES (1, 'admin', 'admin', 1);
	INSERT INTO public.authorities(
	idauth, username, pass, idrol)
	VALUES (2, 'admin2', 'admin2', 1);
